# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c47d42e3a9dda2dae19a9c17868aed5f"
name = "impact-conversion-app-2"
handle = "impact-conversion-app-2"
application_url = "https://fossil-vampire-cells-instances.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ser-test-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_orders,write_products"

[auth]
redirect_urls = [
  "https://fossil-vampire-cells-instances.trycloudflare.com/auth/callback",
  "https://fossil-vampire-cells-instances.trycloudflare.com/auth/shopify/callback",
  "https://fossil-vampire-cells-instances.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled","orders/updated" ]
  uri = "/webhooks"

[pos]
embedded = false
